name: 'covid19-group3'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - vega_datasets
  - altair_saver
  - geopandas
  - pip
  - pip:
    - dash==1.18.1
    - dash_bootstrap_components
    - virtualenv
    - gunicorn
